//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bloggie.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bloggie.Web.Resources.Resource - Copy", typeof(Resource___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Post.
        /// </summary>
        public static string AddNewPost {
            get {
                return ResourceManager.GetString("AddNewPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tag.
        /// </summary>
        public static string AddTag {
            get {
                return ResourceManager.GetString("AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Posts.
        /// </summary>
        public static string AllPosts {
            get {
                return ResourceManager.GetString("AllPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Users.
        /// </summary>
        public static string AllUsers {
            get {
                return ResourceManager.GetString("AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biomass Energy.
        /// </summary>
        public static string BiomassEnergy {
            get {
                return ResourceManager.GetString("BiomassEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geothermal Energy.
        /// </summary>
        public static string GeothermalEnergy {
            get {
                return ResourceManager.GetString("GeothermalEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewable and Sustainable Energy.
        /// </summary>
        public static string RenewableAndSustainableEnergy {
            get {
                return ResourceManager.GetString("RenewableAndSustainableEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Tags.
        /// </summary>
        public static string ShowAllTags {
            get {
                return ResourceManager.GetString("ShowAllTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Energy.
        /// </summary>
        public static string SolarEnergy {
            get {
                return ResourceManager.GetString("SolarEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Future of Renewable Energy Sources.
        /// </summary>
        public static string TheFutureOfRenewableEnergySources {
            get {
                return ResourceManager.GetString("TheFutureOfRenewableEnergySources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Energy.
        /// </summary>
        public static string WaterEnergy {
            get {
                return ResourceManager.GetString("WaterEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Energy.
        /// </summary>
        public static string WindEnergy {
            get {
                return ResourceManager.GetString("WindEnergy", resourceCulture);
            }
        }
    }
}
